name: Release

on:
  push:
    tags:
      - "*"
jobs:
  mac:
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-1
        os:
          - macos-12
          - macos-11
    runs-on: ${{ matrix.os }}
    steps:
      - name: prepare
        run: |
          brew update
          brew install curl zip unzip gnu-sed kerl
          echo "/usr/local/bin" >> $GITHUB_PATH
          git config --global credential.helper store
      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.kerl/${{ matrix.otp }}
          key: otp-install-${{ matrix.otp }}-${{ matrix.os }}

      - name: build erlang
        if: steps.cache.outputs.cache-hit != 'true'
        timeout-minutes: 60
        run: |
          kerl update releases
          kerl build git https://github.com/emqx/otp.git OTP-${{ matrix.otp }} ${{ matrix.otp }}
          kerl install ${{ matrix.otp }} $HOME/.kerl/${{ matrix.otp }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install rebar3
        run: |
          wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
          cp ./rebar3 /usr/local/bin/rebar3

      - name: test build
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          . $HOME/.kerl/${{ matrix.otp }}/activate
          make

      - name: build release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          . $HOME/.kerl/${{ matrix.otp }}/activate
          BUILD_RELEASE=1 make

      - uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: packages
          path: |
            _packages/*.gz
            _packages/*.gz.sha256

  linux:
    strategy:
      fail-fast: false
      matrix:
        builder:
          - 5.1-3
        otp:
          - 25.3.2-1
        elixir:
          - 1.14.5
        arch:
          - amd64
          - arm64
        os:
          - ubuntu22.04
          - ubuntu20.04
          - ubuntu18.04
          - ubuntu16.04
          - debian12
          - debian11
          - debian10
          - debian9
          - el9
          - el8
          - el7
          - amzn2023
          - alpine3.15.1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.arch }}

      - name: test build
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          IMAGE=ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
          docker run --user 1001 --rm -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} $IMAGE bash -euc 'make'

      - name: build release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE=ghcr.io/emqx/emqx-builder/${{ matrix.builder }}:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}
          docker run --user 1001 --rm -v $(pwd):/wd --workdir /wd --platform=linux/${{ matrix.arch }} -e BUILD_RELEASE=1 $IMAGE bash -euc 'make'

      - uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: packages
          path: |
            _packages/*.gz
            _packages/*.gz.sha256

  release:
    runs-on: ubuntu-latest
    needs:
      - mac
      - linux
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: packages
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Erlang Rocksdb NIF ${{ github.ref_name }} Released
          files: packages/*
          draft: false
          prerelease: false
